### ISSUE TITLE
API coordinate system

### ISSUE THREAD

**Issue by andreiltd** [mrDIMAS/hrtf#3]
I'm currently working on wrapping `hrtf` crate in the GStreamer plugin. I was wondering if you could help me to clarify some of the API constraints?

Those are the questions:
- do coordinates passed to the processor have units? meters for instance?
- if not, do they have to be normalized so they are in the range [-1.0, 1.0]?
- is the coordinate system left or right handed?
- what would be an example of static object positions that correspond to 5.1 speaker layout with the listener at `0.0.0` ? E.g. would that work for front left/right speakers:

```
FrontLeft => Vec3 {
     x: -1.45,
     y: 0.0,
     z: 2.5,
 },
FrontRight => Vec3 {
     x: 1.45,
     y: 0.0,
     z: 2.5,
 },
```

Thank you for all amazing work

**Comment by andreiltd** [comment]
It's me again :)

I looked into this a bit further and the problem I'm seeing originates from the code that creates `hrir` binaries. I thought I would draw how the `hrir` coordinates look now and compare to `right handed` and `left handed` coordinate system.

For simplicity I draw only 2d plane, as all the variants have the same understanding of elevation.

This is created by this `octave` code

```matlab
1;

function [x, y, z] = lh_coords(azimuth_rad, elevation_rad)
  azimuth_rad = azimuth_rad .+ pi/2;

  x = cos(elevation_rad) .* cos(azimuth_rad);
  y = zeros(1, numel(x)) .+ sin(elevation_rad);
  z = cos(elevation_rad) .* sin(azimuth_rad);
end

function [x, y, z] = rh_coords(azimuth_rad, elevation_rad)
  [x, y, z] = lh_coords(azimuth_rad, elevation_rad);
  z = -z;
end

function [x, y, z] = curr_hrtf_coords(azimuth_rad, elevation_rad)
  elevation_rad = pi/2 .- elevation_rad;

  x = sin(elevation_rad) .* sin(azimuth_rad);
  y = zeros(1, numel(x)) .+ cos(elevation_rad);
  z = -sin(elevation_rad) .* cos(azimuth_rad);
end

azimuth = 0:30:330;
elevation = 15;

azimuth_rad = azimuth ./ 180 .* pi;
elevation_rad = elevation / 180 * pi;

[x, y, z] = lh_coords(azimuth_rad, elevation_rad);
## [x, y, z] = rh_coords(azimuth_rad, elevation_rad);
## [x, y, z] = curr_hrtf_coords(azimuth_rad, elevation_rad);

plot(x, z, '*', 'MarkerSize', 16)
hold on
grid on

set(gca, 'FontSize', 16)

axis([-1 1 -1 1])
xlabel('x')
ylabel('y')

for n = 1:numel(x)
    text(x(n) + 0.05, z(n), num2str(azimuth(n)), 'FontSize', 16)
end

```

**1. Current `hrir` coordinates:**
![current_coords](https://user-images.githubusercontent.com/7009786/140791904-75c5f5a1-c200-468f-b15b-6ab2420e43f9.png)
**2. How `left handed` should look like:**
![left_handed_coords](https://user-images.githubusercontent.com/7009786/140791975-548769cb-a93b-4161-9bd0-e11f76859c17.png)
**3. How `right handed` should look like:**
![right_handed_coords](https://user-images.githubusercontent.com/7009786/140792015-ae0f8a9b-f464-482a-bd91-a82b5a727a24.png)

**Comment by andreiltd** [comment]
This shows that, `hrtf` crate does not use `Right Handed` system even though docs says so. My understanding of `LH` vs `RH` is that they only differ in `z` sign. But here they differ in sign for both `x` and `z'.

It is also not `a vector from the source to listener` because an elevation is not inverted.

Please let me know what your thoughts. I think the `binaries` generation should be fixed to use `RH` or `LH` or it should be very well documented that the coordinate system is something different.

I can prepare PR if you decide to fix it in https://github.com/mrDIMAS/hrir_sphere_builder

**Comment by mrDIMAS** [comment]
Looks like I messed up with angles, a PR would be nice indeed!

**Comment by andreiltd** [comment]
No worries, this is amazing job. Do you have any preference: LH vs RH? I didn't spend much time looking at what rg3d-sound is doing, but it looks like it assumes LH coordinates for hrtf renderer. If it is so, picking LH coordinates for HRIR would not require any changes there.

**Comment by mrDIMAS** [comment]
The docs says `Hrtf spheres made in *right-handed* coordinate system.`, so it is either to fix generator to use RH or LH and fix the docs. I'd like to have it in right-handed because rg3d game engine uses RH coordinate system too.
