### ISSUE TITLE
how to use with `.mhr` hrtf files?

### ISSUE THREAD

**Issue by SeanTolstoyevski** [mrDIMAS/hrtf#7]
hi,

the file format OpenAL-Soft uses is .mhr, but this crate uses a different file.
Can it be used with OpenAL-Soft's .mhr files?
How do I convert for this?

https://github.com/kcat/openal-soft/blob/master/core/hrtf.cpp#L94

https://github.com/kcat/openal-soft/blob/master/core/hrtf.cpp#L508

**Comment by SeanTolstoyevski** [comment]
Thank you for your answer.

I will try.

**Comment by ThreeDeeJay** [comment]
@SeanTolstoyevski If you can extract the impulse response WAVs, you can put together a [.DEF (OpenAL Soft definition file)](https://github.com/kcat/openal-soft/blob/master/utils/makemhr/loaddef.cpp) like [IRC_1005.def](https://github.com/kcat/openal-soft/blob/master/utils/IRC_1005.def) then use [makemhr](https://github.com/kcat/openal-soft/releases/tag/makemhr) to convert it to MHR.
I once made a [.def](https://github.com/ThreeDeeJay/HRIR-Batch-Converters/blob/master/Generate%20DEF%20-%20SADIE_xx%20%5BOpenAL%20Soft%5D.bat) manually and it was extremely tedious, so I've always wanted a script that parses coordinates from WAV filenames into a .def file, but I'm yet to find such a thing.
